### ISSUE TITLE
Find out where DeviceType gets determined and set it in the UwbSession when constructing it

### ISSUE THREAD

**Issue by forwardpointer** [microsoft/nearobject-framework#158]
#154 changes the constructor of UwbSession to accept a DeviceType, defaulting to Controller. Nothing in the codebase explicitly sets the DeviceType so all UwbSession instances will be Controller. We need to determine where that information comes from and set it accordingly.

**Comment by corbin-phipps** [comment]
DeviceType is a parameter that comes from OOB. We now know that UwbSession is constructed by the WinRT APIs which have knowledge of the OOB parameters (including DeviceType) through the NearObjectIdentityToken, so I am closing this issue.
