### ISSUE TITLE
nocli: uwb range stop command should be removed

### ISSUE THREAD

**Issue by corbin-phipps** [microsoft/nearobject-framework#190]
**Is your feature request related to a problem? Please describe.**
There is no point in keeping the "uwb range stop" command because a ranging session can only be stopped after it is started, but once a session is started with "uwb range start", it will run continuously until it receives a stop signal (CTRL+C, timeout, etc.).

**Describe the solution you'd like**
Remove "uwb range stop" command.

**Describe alternatives you've considered**
If this subcommand is removed, then the only remaining subcommand under "uwb range" is "start". Perhaps this can be combined into a single command?

**Comment by abeltrano** [comment]
With the new functionality to create a `UwbSession` only from a session id, this command could be used in isolation to stop a pre-existing session, eg.

```
> nocli.exe uwb range start <args> --sessionId 1234 --dontWait
# nocli.exe starts session and exits immediately
> nocli.exe uwb range stop --sessionId 1234
# nocli.exe stops the session and exits
```

See the `nocli uwb raw sessiondeinit` implementation for an example of how this can work.
