### ISSUE TITLE
nocli: "uwb" subcommand should be renamed

### ISSUE THREAD

**Issue by corbin-phipps** [microsoft/nearobject-framework#191]
**Is your feature request related to a problem? Please describe.**
We received feedback during the demo that the "uwb" subcommand should be renamed to "driver" or something similar so that the two top-level subcommands are "driver" and "service"

**Describe the solution you'd like**
Rename "uwb" to "driver".

**Describe alternatives you've considered**
We could consider other names for the top-level subcommands instead of "driver" and "service".

**Comment by abeltrano** [comment]
We can also have command aliases. Since the current names make sense (at least `uwb`), I propose we add aliases with any additional names we think make sense.
