### ISSUE TITLE
actually deregister the callbacks where it's necessary

### ISSUE THREAD

**Issue by forwardpointer** [microsoft/nearobject-framework#225]
basically wherever in the code with a TODO statement about deregistering the callback, do so

**Comment by forwardpointer** [comment]
Currently I see one issue with our design is that it doesn't allow for granularity of registering/deregistering single callbacks for specific events. Either the entire structure of session callbacks for one single session is deregistered or it is kept registered even when it is missing a callback for a specific event. This kind of ruins the point of registering for specific events, in my opinion. 

A proposed fix would be to have individual types for each event callback, at least stored internally by UwbConnector. That way, it could easily deregister individual event callbacks should they go stale. However, if we want the client of UwbConnector to be able to deregister individual callbacks as well then it needs to store a token for each callback it registers. This may or may not be desirable.

**Comment by abeltrano** [comment]
To deregister/opt-out of an individual callback, can the caller just set the `UwbRegisteredSessionEventCallbacks` callback member to `nullptr`? When the connector tries to execute it, it'll see a `nullptr` and ignore it.
