### ISSUE TITLE
Bug: Typo in uwb::protocol::fira::UwbSessionUpdateMulicastListStatus

### ISSUE THREAD

**Issue by corbin-phipps** [microsoft/nearobject-framework#249]
**Describe the bug**
There is a typo in `uwb::protocol::fira::UwbSessionUpdateMulicastListStatus`. This should be `uwb::protocol::fira::UwbSessionUpdateMulticastListStatus`

**Comment by forwardpointer** [comment]
nice eye! totally missed this
